# `name` value will appear "as is" in the badge.
# See https://docs.github.com/en/actions/configuring-and-managing-workflows/configuring-a-workflow#adding-a-workflow-status-badge-to-your-repository
# yamllint --format github .github/workflows/commit.yaml
---
name: "build"

on:
  push:  # We run tests on non-tagged pushes to main
    tags: ''
    branches: main
    paths-ignore:
      - '**/*.md'
  pull_request:  # We also run tests on pull requests targeted at the main branch.
    branches: main
    paths-ignore:
      - '**/*.md'
  # workflow_dispatch will let us manually trigger the workflow from GitHub actions dashboard.
  # For example, you can try to build a branch without raising a pull request.
  # See https://docs.github.com/en/free-pro-team@latest/actions/managing-workflow-runs/manually-running-a-workflow
  workflow_dispatch:

jobs:
  check:
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        go-version:  # Note: Go only supports 2 versions: https://go.dev/doc/devel/release#policy
          - "1.18"
          - "1.19"

    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-go@v3
        with:  # not cache: true as we also need to cache golint
          go-version: ${{ matrix.go-version }}

      - uses: actions/cache@v3
        with:
          path: |
            ~/.cache/go-build
            ~/.cache/golangci-lint
            ~/go/pkg/mod
            ~/go/bin
          key: check-${{ runner.os }}-go-${{ matrix.go-version }}-${{ hashFiles('**/go.sum', 'Makefile') }}

      - name: "Set up wat2wasm"
        run: |  # Needed for testdata. wabt includes wat2wasm.
          wabt_version=1.0.30
          wabt_url=https://github.com/WebAssembly/wabt/releases/download/${wabt_version}/wabt-${wabt_version}-ubuntu.tar.gz
          curl -sSL ${wabt_url} | tar --strip-components 2 -C /usr/local/bin -xzf - wabt-${wabt_version}/bin/wat2wasm

      - run: make testdata

      - run: make check

  test:
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        go-version:  # Note: Go only supports 2 versions: https://go.dev/doc/devel/release#policy
          - "1.18"
          - "1.19"

    steps:
      - name: "Checkout"
        uses: actions/checkout@v3

      - name: "Set up Go"
        uses: actions/setup-go@v3
        with:
          go-version: ${{ matrix.go-version }}
          cache: true

      - name: "Test"
        run: make test
